server.port: 8080
server.request.maxRequestSize: 2Mb


server.session.state.jwt:
  requestUseHeader: true
  responseUseHeader: true

solon.app:
  name: demoapi
  group: water


solon.cloud.water:
  server: water

