server.port: 9020
server.request.maxRequestSize: 2Mb

solon.app:
  name: demoapi
  group: demo

solon.cloud.water:
  server: water
  config:
    loadKey: demoapi.config
  log:
    default: demoapi_log_slf4j

